name: merge2mkv
description: Automatically merge downloaded series or movies to the common convention used by media servers.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  path: ^1.8.2
  intl: ^0.17.0
  async: ^2.11.0
  provider: ^6.0.4
  equatable: ^2.0.5
  diacritic: ^0.1.3
  fluent_ui: ^4.0.3+1
  translator: ^0.1.7
  pluto_grid: ^5.4.9
  file_picker: ^5.2.2
  collection: ^1.16.0
  url_launcher: ^6.1.6
  desktop_drop: ^0.4.0
  system_theme: ^2.0.0
  window_manager: ^0.3.1
  path_provider: ^2.0.14
  multi_split_view: ^2.1.0
  flutter_acrylic: ^1.0.0+2
  shared_preferences: ^2.0.15
  fc_native_video_thumbnail: ^0.4.0
  

dev_dependencies:
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/mkvmerge/
    - assets/mediainfo/

