name: Build and Release Windows
on: 
    workflow_dispatch:

jobs:
    build_and_release_windows:
        name: Build and Release for Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Prepare folders
              run: |
                mkdir keys
            - name: Setup secret keys
              run: |
                echo ${{ secrets.CERTIFICATE }} | base64 --decode > keys/CERTIFICATE.pfx
            - name: Get app version from pubspec.yaml
              run: |
                choco install yq
                $version=(yq -r '.version | split("+")[0]' pubspec.yaml)
                echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

            - uses: subosito/flutter-action@v2
            - name: Enable windows build
              run: flutter config --enable-windows-desktop
            - name: Build windows release artifacts
              run: flutter build windows --release
            - name: Archive and compress release artifacts
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: mkv_profile-${{env.APP_VERSION}}-windows.zip
                directory: build/windows/runner/Release
            - name: Create msix installer
              run: |
                flutter pub run msix:create `
                --certificate-password=${{ secrets.CERTIFICATE_PASSWORD }} `
                --certificate-path=${{ github.workspace }}/keys/CERTIFICATE.pfx `
                --output-path=build/windows/runner/Release
            - name: Rename generated default file name of msix installer
              run: ren build/windows/runner/Release/mkv_profile.msix mkv_profile-"${{env.APP_VERSION}}"-windows.msix
            - name: Upload to Github release
              uses: softprops/action-gh-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v${{env.APP_VERSION}}
                files: |
                  build/windows/runner/Release/mkv_profile-"${{env.APP_VERSION}}"-windows.zip
                  build/windows/runner/Release/mkv_profile-"${{env.APP_VERSION}}"-windows.msix